#!/bin/bash

if [[ "$(basename $(pwd)" != *"fet"* ]]; then
    echo "This script needs to be ran from the same dir as the .fet files." && exit 1
fi

[ ! -d "target/" ] && mkdir -pv "target/"

fet_file="$1"
base_name="$(echo $1 | awk -F. '{print $1}')"
fetlang -o target/"$base_name" -O "$fet_file"