#!/bin/bash

# Ensure script is ran from correct dir.
if [[ "$(basename "$(pwd)")" != *"fet"* ]]; then
    echo "This script needs to be ran from the same dir as the .fet files." && exit 1
fi

# Make target dir if non-existent.
[ ! -d "target/" ] && mkdir -pv "target/"

fet_file="$1" # Set to first argument.
base_name="$(echo "$1" | awk -F. '{print $1}')" # blah.fet -> blah
fetlang -o target/"$base_name" -O "$fet_file" # blah.fet compiles to target/blah

# Test.
./target/"$base_name"
